### PR TITLE
Downgrade to go-header 0.5.0 for golangci-lint compatibility

### LINKED ISSUE #3788: golangci-lint using make lint-new is broken
**Describe the bug**

Golangci-lint is broken in `tools/`

**To Reproduce**

```console
$ make lint-new

# github.com/golangci/golangci-lint/v2/pkg/golinters/goheader
/home/tsaarni/go/pkg/mod/github.com/golangci/golangci-lint/v2@v2.12.2/pkg/golinters/goheader/goheader.go:17:20: undefined: goheader.Configuration
/home/tsaarni/go/pkg/mod/github.com/golangci/golangci-lint/v2@v2.12.2/pkg/golinters/goheader/goheader.go:19:20: undefined: goheader.Configuration
/home/tsaarni/go/pkg/mod/github.com/golangci/golangci-lint/v2@v2.12.2/pkg/golinters/goheader/goheader.go:42:54: undefined: goheader.Configuration
/home/tsaarni/go/pkg/mod/github.com/golangci/golangci-lint/v2@v2.12.2/pkg/golinters/goheader/goheader.go:58:29: undefined: goheader.WithTemplate
/home/tsaarni/go/pkg/mod/github.com/golangci/golangci-lint/v2@v2.12.2/pkg/golinters/goheader/goheader.go:58:53: too many arguments in call to goheader.New
        have (unknown type, unknown type)
        want (*"github.com/denis-tingaikin/go-header".Settings)
/home/tsaarni/go/pkg/mod/github.com/golangci/golangci-lint/v2@v2.12.2/pkg/golinters/goheader/goheader.go:58:62: undefined: goheader.WithValues
/home/tsaarni/go/pkg/mod/github.com/golangci/golangci-lint/v2@v2.12.2/pkg/golinters/goheader/goheader.go:66:14: a.Analyze undefined (type *analysis.Analyzer has no field or method Analyze)
/home/tsaarni/go/pkg/mod/github.com/golangci/golangci-lint/v2@v2.12.2/pkg/golinters/goheader/goheader.go:66:32: undefined: goheader.Target
...
```

**Expected behavior**

**Environment:**

**Additional context**

Current golangci-lint version is incompatible with go-header 1.0.0 which was bumped by #3349

The github workflow works because it does not use `go tool` and therefore `tools/`

### PR DESCRIPTION
**Pull request by tsaarni**
## Description

This PR reverts `github.com/denis-tingaikin/go-header` back to version 0.5.0 to fix `make lint-new`.

## Rationale

The version of `github.com/denis-tingaikin/go-header` was bumped to 1.0.0 in #3349. Running golangci-lint via `go tool -modfile=tools/go.mod` stopped working at that point because latest golangci-lint version does not compile with 1.0.0. 

Linting in CI workflow still works since it does not compile golangci-lint with `tools/` deps.

Golangci-lint itself still uses version 0.5.0 ([link](https://github.com/golangci/golangci-lint/blob/c0d3ddc9cf3faa61a4e378e879ece580256d76e5/go.mod#L56)). The update in #3349 might have been done by running `go get -u`. I found no vulnerabilities reported for 0.5.0 version.

Resolves: #3788

## Acknowledgements

 - [x] By contributing this change, I certify I have not used generative AI
       (GitHub Copilot, Cursor, Claude Code, &c) in authoring these changes or
       filling out the pull request description or associated issue.
 - [x] By contributing this change, I certify I have signed-off on the
       [DCO ownership](https://developercertificate.org/) statement
       and this change did not use post-BUSL-licensed code from HashiCorp.
       Existing MPL-licensed code is still allowed, subject to attribution.
       Code authored by yourself and submitted to HashiCorp for inclusion is
       also allowed.

### CODE REVIEW

**Review by cipherboy — APPROVED** [review]
Thanks @tsaarni!
