### PR TITLE
Forward generate-root requests to active node

### LINKED ISSUE #2987: Generate-root fails when request is routed to standby node
**Describe the bug**

The `/sys/generate-root` endpoint ([now deprecated](https://openbao.org/docs/deprecation/#unauthenticated-rekey--root-rotation-endpoints)) fails when a load balancer forwards the request to a standby instance:

```http
HTTP/1.1 400 Bad Request

{"errors":["Vault is in standby mode"]}
```

**To Reproduce**

```
# Create configs.
rm -rf testdata
mkdir -p testdata/bao-node0 testdata/bao-node1

cat <<EOF > testdata/node0.hcl
listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = true
  disable_unauthed_generate_root_endpoints = false
}
storage "raft" {
  path    = "testdata/bao-node0"
  node_id = "node0"
}
api_addr     = "http://127.0.0.1:8200"
cluster_addr = "http://127.0.0.1:8201"
EOF

cat <<EOF > testdata/node1.hcl
listener "tcp" {
  address     = "127.0.0.1:8202"
  tls_disable = true
  disable_unauthed_generate_root_endpoints = false
}
storage "raft" {
  path    = "testdata/bao-node1"
  node_id = "node1"
}
api_addr     = "http://127.0.0.1:8202"
cluster_addr = "http://127.0.0.1:8203"
EOF

# Start servers.
bin/bao server -config=testdata/node0.hcl  # becomes active
bin/bao server -config=testdata/node1.hcl  # becomes standby

# Initialize and unseal node0.
export BAO_ADDR=http://127.0.0.1:8200
bin/bao operator init -key-shares=1 -key-threshold=1 -format=json > testdata/init.json
UNSEAL_KEY=$(jq -r '.unseal_keys_b64[0]' testdata/init.json)
ROOT_TOKEN=$(jq -r '.root_token' testdata/init.json)
bin/bao operator unseal "$UNSEAL_KEY"
bin/bao login "$ROOT_TOKEN"

# Join and unseal node1.
export BAO_ADDR=http://127.0.0.1:8202
bin/bao operator raft join http://127.0.0.1:8200
bin/bao operator unseal "$UNSEAL_KEY"

# Try generate-root on node1 (standby).
BAO_ADDR=http://127.0.0.1:8202 bin/bao operator generate-root -init
# BUG:  400 Vault is in standby mode
# Expected: starts generation (forwarded to active node0)

# Same command on the active node works fine.
BAO_ADDR=http://127.0.0.1:8200 bin/bao operator generate-root -init
# Returns: Nonce, Started=true, etc.
```

The above exercises only `/v1/sys/generate-root/attempt` but similarly `/v1/sys/generate-root/update` will fail

```
# Generate OTP and init on node0 (active)
OTP=$(BAO_ADDR=http://127.0.0.1:8200 bin/bao operator generate-root -generate-otp)
NONCE=$(BAO_ADDR=http://127.0.0.1:8200 bin/bao operator generate-root -init -otp="$OTP" -format=json | jq -r '.nonce')

# Send /update to node1 (standby)
BAO_ADDR=http://127.0.0.1:8202 bin/bao operator generate-root \
  -nonce="$NONCE" \
  -otp="$OTP" \
  "$UNSEAL_KEY"
# BUG:  500 Vault is in standby mode
```

**Expected behavior**

The `generate-root` endpoint should work regardless of which instance receives the request.

**Environment:**
* OpenBao Server Version: main

**Additional context**

The regression happened in 9832b5c75d4aeff0aaea4a96c7815ce3b9dbe887 (#1986)

### PR DESCRIPTION
**Pull request by tsaarni**
## Description

Generating a new root token fails when a load balancer forwards the request to a standby instance.

This PR ensures that the standby instance forwards both `/v1/sys/generate-root/attempt` and `/v1/sys/generate-root/update` requests to the active node for processing.

## Rationale

Resolves: #2987

This fixes regression introduced in 9832b5c75d4aeff0aaea4a96c7815ce3b9dbe887 (#1986)

## Acknowledgements

 - [x] By contributing this change, I certify I have not used generative AI
       (GitHub Copilot, Cursor, Claude Code, &c) in authoring these changes or
       filling out the pull request description or associated issue.
 - [x] By contributing this change, I certify I have signed-off on the
       [DCO ownership](https://developercertificate.org/) statement
       and this change did not use post-BUSL-licensed code from HashiCorp.
       Existing MPL-licensed code is still allowed, subject to attribution.
       Code authored by yourself and submitted to HashiCorp for inclusion is
       also allowed.

### CODE REVIEW

**Comment by tsaarni** [comment]
I manually verified this change by following the steps described in #2987.

**Comment by tsaarni** [comment]
> I manually verified this change by following the steps described in #2987.

Tests were failing in recovery mode

```
recovery_test.go:94: Error making API request.

    URL: PUT https://127.0.0.1:45617/v1/sys/generate-recovery-token/attempt
    Code: 503. Errors:

    * node is not active
```

fixed by adding `core.HAEnabled()` as pre-condition to forwarding.

**Comment by cipherboy** [comment]
https://github.com/openbao/openbao/blob/dbd8debea1eed95cb5a38cf3ba65ed872766feea/http/sys_generate_root.go#L123

"Attemptialize"

**Comment by cipherboy** [comment]
I replied on #2987 just in case anyone's looking to review this.

**Comment by tsaarni** [comment]
> "Attemptialize"

Sounds bit similar to me as "upsert" but I see nobody has ever used "Attemptialize" anywhere else in the world, so maybe just a joke or typo? Anyways, it was not from me, it has been there in the code for 11 years :-D

**Comment by tsaarni** [comment]
Closing this in favor of #3006
